module.exports =[
    {
        city: "Cairo", 
        latitude: "30.0561", 
        longitude: "31.2394", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Qāhirah", 
        capital: "primary", 
        population: "19372000", 
        population_proper: "9500000"
    }, 
    {
        city: "Giza", 
        latitude: "29.9870", 
        longitude: "31.2118", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Jīzah", 
        capital: "admin", 
        population: "5598402", 
        population_proper: "5598402"
    }, 
    {
        city: "Alexandria", 
        latitude: "31.2000", 
        longitude: "29.9167", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Iskandarīyah", 
        capital: "admin", 
        population: "4870000", 
        population_proper: "4870000"
    }, 
    {
        city: "Madīnat as Sādis min Uktūbar", 
        latitude: "29.9361", 
        longitude: "30.9269", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Jīzah", 
        capital: "", 
        population: "1500000", 
        population_proper: "1500000"
    }, 
    {
        city: "Shubrā al Khaymah", 
        latitude: "30.1286", 
        longitude: "31.2422", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Qalyūbīyah", 
        capital: "", 
        population: "1025569", 
        population_proper: "1025569"
    }, 
    {
        city: "Al Manşūrah", 
        latitude: "31.0500", 
        longitude: "31.3833", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Ad Daqahlīyah", 
        capital: "admin", 
        population: "960423", 
        population_proper: "960423"
    }, 
    {
        city: "Ḩalwān", 
        latitude: "29.8419", 
        longitude: "31.3342", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Qāhirah", 
        capital: "", 
        population: "619293", 
        population_proper: "619293"
    }, 
    {
        city: "Al Maḩallah al Kubrá", 
        latitude: "30.9667", 
        longitude: "31.1667", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Gharbīyah", 
        capital: "", 
        population: "543271", 
        population_proper: "543271"
    }, 
    {
        city: "Port Said", 
        latitude: "31.2500", 
        longitude: "32.2833", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Būr Sa‘īd", 
        capital: "admin", 
        population: "524433", 
        population_proper: "524433"
    }, 
    {
        city: "Suez", 
        latitude: "29.9667", 
        longitude: "32.5333", 
        country: "Egypt", 
        iso2: "EG", 
        state: "As Suways", 
        capital: "admin", 
        population: "485342", 
        population_proper: "485342"
    }, 
    {
        city: "Ţanţā", 
        latitude: "30.7833", 
        longitude: "31.0000", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Gharbīyah", 
        capital: "admin", 
        population: "429503", 
        population_proper: "429503"
    }, 
    {
        city: "Asyūţ", 
        latitude: "27.1869", 
        longitude: "31.1714", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Asyūţ", 
        capital: "admin", 
        population: "389307", 
        population_proper: "389307"
    }, 
    {
        city: "Al Fayyūm", 
        latitude: "29.3000", 
        longitude: "30.8333", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Fayyūm", 
        capital: "admin", 
        population: "315940", 
        population_proper: "315940"
    }, 
    {
        city: "Az Zaqāzīq", 
        latitude: "30.5667", 
        longitude: "31.5000", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Ash Sharqīyah", 
        capital: "admin", 
        population: "302840", 
        population_proper: "302840"
    }, 
    {
        city: "Ismailia", 
        latitude: "30.5833", 
        longitude: "32.2667", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Ismā‘īlīyah", 
        capital: "admin", 
        population: "293184", 
        population_proper: "293184"
    }, 
    {
        city: "Aswān", 
        latitude: "24.0889", 
        longitude: "32.8997", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Aswān", 
        capital: "admin", 
        population: "267913", 
        population_proper: "267913"
    }, 
    {
        city: "Kafr ad Dawwār", 
        latitude: "31.1417", 
        longitude: "30.1272", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Buḩayrah", 
        capital: "", 
        population: "262748", 
        population_proper: "262748"
    }, 
    {
        city: "Damanhūr", 
        latitude: "31.0500", 
        longitude: "30.4667", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Buḩayrah", 
        capital: "admin", 
        population: "244043", 
        population_proper: "244043"
    }, 
    {
        city: "Al Minyā", 
        latitude: "28.0833", 
        longitude: "30.7500", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minyā", 
        capital: "admin", 
        population: "236043", 
        population_proper: "236043"
    }, 
    {
        city: "Damietta", 
        latitude: "31.4167", 
        longitude: "31.8214", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Dumyāţ", 
        capital: "admin", 
        population: "206664", 
        population_proper: "206664"
    }, 
    {
        city: "Luxor", 
        latitude: "25.6969", 
        longitude: "32.6422", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Uqşur", 
        capital: "admin", 
        population: "202232", 
        population_proper: "202232"
    }, 
    {
        city: "Qinā", 
        latitude: "26.1667", 
        longitude: "32.7167", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Qinā", 
        capital: "admin", 
        population: "201191", 
        population_proper: "201191"
    }, 
    {
        city: "Sūhāj", 
        latitude: "26.5606", 
        longitude: "31.6917", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Sūhāj", 
        capital: "admin", 
        population: "193931", 
        population_proper: "193931"
    }, 
    {
        city: "Banī Suwayf", 
        latitude: "29.0667", 
        longitude: "31.0833", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Banī Suwayf", 
        capital: "admin", 
        population: "193048", 
        population_proper: "193048"
    }, 
    {
        city: "Shibīn al Kawm", 
        latitude: "30.5920", 
        longitude: "30.9000", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minūfīyah", 
        capital: "admin", 
        population: "182900", 
        population_proper: "182900"
    }, 
    {
        city: "Al ‘Arīsh", 
        latitude: "31.1249", 
        longitude: "33.8006", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Shamāl Sīnā’", 
        capital: "admin", 
        population: "178651", 
        population_proper: "128855"
    }, 
    {
        city: "Al Ghardaqah", 
        latitude: "27.2578", 
        longitude: "33.8117", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Baḩr al Aḩmar", 
        capital: "admin", 
        population: "160901", 
        population_proper: "160901"
    }, 
    {
        city: "Banhā", 
        latitude: "30.4628", 
        longitude: "31.1797", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Qalyūbīyah", 
        capital: "admin", 
        population: "157701", 
        population_proper: "157701"
    }, 
    {
        city: "Kafr ash Shaykh", 
        latitude: "31.1000", 
        longitude: "30.9500", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Kafr ash Shaykh", 
        capital: "admin", 
        population: "147393", 
        population_proper: "147393"
    }, 
    {
        city: "Disūq", 
        latitude: "31.1308", 
        longitude: "30.6479", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Kafr ash Shaykh", 
        capital: "", 
        population: "143404", 
        population_proper: "143404"
    }, 
    {
        city: "Bilbays", 
        latitude: "30.4167", 
        longitude: "31.5667", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Ash Sharqīyah", 
        capital: "", 
        population: "141285", 
        population_proper: "141285"
    }, 
    {
        city: "Mallawī", 
        latitude: "27.7306", 
        longitude: "30.8425", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minyā", 
        capital: "", 
        population: "139929", 
        population_proper: "139929"
    }, 
    {
        city: "Idfū", 
        latitude: "24.9781", 
        longitude: "32.8789", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Aswān", 
        capital: "", 
        population: "133772", 
        population_proper: "133772"
    }, 
    {
        city: "Mīt Ghamr", 
        latitude: "30.7192", 
        longitude: "31.2628", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Ad Daqahlīyah", 
        capital: "", 
        population: "121039", 
        population_proper: "121039"
    }, 
    {
        city: "Munūf", 
        latitude: "30.4667", 
        longitude: "30.9333", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minūfīyah", 
        capital: "", 
        population: "117240", 
        population_proper: "117240"
    }, 
    {
        city: "Jirjā", 
        latitude: "26.3419", 
        longitude: "31.8894", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Sūhāj", 
        capital: "", 
        population: "102597", 
        population_proper: "102597"
    }, 
    {
        city: "Akhmīm", 
        latitude: "26.5642", 
        longitude: "31.7461", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Sūhāj", 
        capital: "", 
        population: "101509", 
        population_proper: "101509"
    }, 
    {
        city: "Ziftá", 
        latitude: "30.7119", 
        longitude: "31.2394", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Gharbīyah", 
        capital: "", 
        population: "93740", 
        population_proper: "93740"
    }, 
    {
        city: "Samālūţ", 
        latitude: "28.3000", 
        longitude: "30.7167", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minyā", 
        capital: "", 
        population: "91475", 
        population_proper: "91475"
    }, 
    {
        city: "Manfalūţ", 
        latitude: "27.3128", 
        longitude: "30.9703", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Asyūţ", 
        capital: "", 
        population: "82585", 
        population_proper: "82585"
    }, 
    {
        city: "Banī Mazār", 
        latitude: "28.5000", 
        longitude: "30.8000", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minyā", 
        capital: "", 
        population: "79553", 
        population_proper: "79553"
    }, 
    {
        city: "Armant", 
        latitude: "25.6167", 
        longitude: "32.5333", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Qinā", 
        capital: "", 
        population: "76457", 
        population_proper: "76457"
    }, 
    {
        city: "Maghāghah", 
        latitude: "28.6483", 
        longitude: "30.8422", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minyā", 
        capital: "", 
        population: "75657", 
        population_proper: "75657"
    }, 
    {
        city: "Kawm Umbū", 
        latitude: "24.4667", 
        longitude: "32.9500", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Aswān", 
        capital: "", 
        population: "71596", 
        population_proper: "71596"
    }, 
    {
        city: "Būr Fu’ād", 
        latitude: "31.2314", 
        longitude: "32.3253", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Būr Sa‘īd", 
        capital: "", 
        population: "70417", 
        population_proper: "70417"
    }, 
    {
        city: "Al Qūşīyah", 
        latitude: "27.4403", 
        longitude: "30.8183", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Asyūţ", 
        capital: "", 
        population: "69388", 
        population_proper: "69388"
    }, 
    {
        city: "Rosetta", 
        latitude: "31.4014", 
        longitude: "30.4194", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Buḩayrah", 
        capital: "", 
        population: "68947", 
        population_proper: "68947"
    }, 
    {
        city: "Isnā", 
        latitude: "25.2933", 
        longitude: "32.5564", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Qinā", 
        capital: "", 
        population: "68656", 
        population_proper: "68656"
    }, 
    {
        city: "Maţrūḩ", 
        latitude: "31.3333", 
        longitude: "27.2333", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Maţrūḩ", 
        capital: "", 
        population: "68339", 
        population_proper: "68339"
    }, 
    {
        city: "Abnūb", 
        latitude: "27.2667", 
        longitude: "31.1500", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Asyūţ", 
        capital: "", 
        population: "67526", 
        population_proper: "67526"
    }, 
    {
        city: "Hihyā", 
        latitude: "30.6687", 
        longitude: "31.5904", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Ash Sharqīyah", 
        capital: "", 
        population: "66702", 
        population_proper: "66702"
    }, 
    {
        city: "Samannūd", 
        latitude: "30.9622", 
        longitude: "31.2425", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Gharbīyah", 
        capital: "", 
        population: "57177", 
        population_proper: "57177"
    }, 
    {
        city: "Dandarah", 
        latitude: "26.1422", 
        longitude: "32.6697", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Qinā", 
        capital: "", 
        population: "53109", 
        population_proper: "53109"
    }, 
    {
        city: "Al Khārjah", 
        latitude: "25.4400", 
        longitude: "30.5500", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Wādī al Jadīd", 
        capital: "admin", 
        population: "49991", 
        population_proper: "49991"
    }, 
    {
        city: "Al Balyanā", 
        latitude: "26.2329", 
        longitude: "31.9993", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Sūhāj", 
        capital: "", 
        population: "46997", 
        population_proper: "46997"
    }, 
    {
        city: "Maţāy", 
        latitude: "28.4167", 
        longitude: "30.7833", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minyā", 
        capital: "", 
        population: "46903", 
        population_proper: "46903"
    }, 
    {
        city: "Naj‘ Ḩammādī", 
        latitude: "26.0500", 
        longitude: "32.2500", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Qinā", 
        capital: "", 
        population: "45038", 
        population_proper: "45038"
    }, 
    {
        city: "Şān al Ḩajar al Qiblīyah", 
        latitude: "30.9769", 
        longitude: "31.8800", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Ash Sharqīyah", 
        capital: "", 
        population: "43157", 
        population_proper: "43157"
    }, 
    {
        city: "Dayr Mawās", 
        latitude: "27.6414", 
        longitude: "30.8494", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minyā", 
        capital: "", 
        population: "40640", 
        population_proper: "40640"
    }, 
    {
        city: "Ihnāsyā al Madīnah", 
        latitude: "29.0856", 
        longitude: "30.9344", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Banī Suwayf", 
        capital: "", 
        population: "40001", 
        population_proper: "40001"
    }, 
    {
        city: "Darāw", 
        latitude: "24.4003", 
        longitude: "32.9306", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Aswān", 
        capital: "", 
        population: "38400", 
        population_proper: "38400"
    }, 
    {
        city: "Abū Qīr", 
        latitude: "31.3167", 
        longitude: "30.0667", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Iskandarīyah", 
        capital: "", 
        population: "37997", 
        population_proper: "37997"
    }, 
    {
        city: "Fāraskūr", 
        latitude: "31.3297", 
        longitude: "31.7147", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Dumyāţ", 
        capital: "", 
        population: "36850", 
        population_proper: "36850"
    }, 
    {
        city: "Ra’s Ghārib", 
        latitude: "28.3597", 
        longitude: "33.0775", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Baḩr al Aḩmar", 
        capital: "", 
        population: "32318", 
        population_proper: "32318"
    }, 
    {
        city: "Al Ḩusaynīyah", 
        latitude: "30.8612", 
        longitude: "31.9190", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Ash Sharqīyah", 
        capital: "", 
        population: "30825", 
        population_proper: "30825"
    }, 
    {
        city: "Safājā", 
        latitude: "26.7517", 
        longitude: "33.9344", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Baḩr al Aḩmar", 
        capital: "", 
        population: "28261", 
        population_proper: "28261"
    }, 
    {
        city: "Qiman al ‘Arūs", 
        latitude: "29.3005", 
        longitude: "31.1683", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Banī Suwayf", 
        capital: "", 
        population: "28246", 
        population_proper: "28246"
    }, 
    {
        city: "Qahā", 
        latitude: "30.2833", 
        longitude: "31.2000", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Qalyūbīyah", 
        capital: "", 
        population: "26694", 
        population_proper: "26694"
    }, 
    {
        city: "Al Karnak", 
        latitude: "25.7184", 
        longitude: "32.6581", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Uqşur", 
        capital: "", 
        population: "26488", 
        population_proper: "26488"
    }, 
    {
        city: "Hirrīyat Raznah", 
        latitude: "30.6028", 
        longitude: "31.5372", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Ash Sharqīyah", 
        capital: "", 
        population: "24359", 
        population_proper: "24359"
    }, 
    {
        city: "Al Quşayr", 
        latitude: "26.1091", 
        longitude: "34.2760", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Baḩr al Aḩmar", 
        capital: "", 
        population: "24344", 
        population_proper: "24344"
    }, 
    {
        city: "Kafr Shukr", 
        latitude: "30.5470", 
        longitude: "31.2673", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minūfīyah", 
        capital: "", 
        population: "23390", 
        population_proper: "23390"
    }, 
    {
        city: "Sīwah", 
        latitude: "29.2000", 
        longitude: "25.5167", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Maţrūḩ", 
        capital: "", 
        population: "23080", 
        population_proper: "23080"
    }, 
    {
        city: "Kafr Sa‘d", 
        latitude: "31.3557", 
        longitude: "31.6848", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Dumyāţ", 
        capital: "", 
        population: "22500", 
        population_proper: "22500"
    }, 
    {
        city: "Shārūnah", 
        latitude: "28.5940", 
        longitude: "30.8516", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Al Minyā", 
        capital: "", 
        population: "22221", 
        population_proper: "22221"
    }, 
    {
        city: "Aţ Ţūr", 
        latitude: "28.2333", 
        longitude: "33.6167", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Janūb Sīnā’", 
        capital: "admin", 
        population: "12733", 
        population_proper: "12733"
    }, 
    {
        city: "Rafaḩ", 
        latitude: "31.2820", 
        longitude: "34.2387", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Shamāl Sīnā’", 
        capital: "minor", 
        population: "", 
        population_proper: ""
    }, 
    {
        city: "Ash Shaykh Zuwayd", 
        latitude: "31.2119", 
        longitude: "34.1106", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Shamāl Sīnā’", 
        capital: "minor", 
        population: "", 
        population_proper: ""
    }, 
    {
        city: "Bi’r al ‘Abd", 
        latitude: "31.0000", 
        longitude: "33.0167", 
        country: "Egypt", 
        iso2: "EG", 
        state: "Shamāl Sīnā’", 
        capital: "minor", 
        population: "", 
        population_proper: ""
    }
    ]